### ISSUE TITLE
La connexion utilisateur (#2 sur Backlog )

### ISSUE THREAD

**Issue by Eorlingalss** [AAAsso/aaaccueil#1]
- [x] "joli" formulaire de connexion
  - [x] form dans la nav bar
  - [x] éditer placeholder login pour y mettre "Adresse mail ou Pseudo"
- [x] formulaire de connexion qui fonctionne
    - [x] messages
      - [x] si login !ok : message "login incorrect"
      - [x] si login ok && mdp !ok : message "mdp incorrect"
    - [x] fonctionnement
      - [x] si login ok && mdp ok : 
        - [x] redirection vers accueil
        - [x] affichage du dropdown utilisateur
        - [x] affichage de l'icône de notifs

**Comment by LucileDT** [comment]
Pour les messages, utiliser : http://getbootstrap.com/components/#alerts-dismissible
Mettre au dessus du fil d'arianne

**Comment by Parmifer** [comment]
Pour les 10 tentatives, ça sera fait plus tard, mais ça me semble important.
Il faut cependant d’or et déjà réfléchir à comment faire ça techniquement, pour que ça soit à la fois propre, performant et secure.

**Comment by LucileDT** [comment]
@Parmifer ok, je rajoute ça dans le backlog ?

**Comment by Parmifer** [comment]
Oui stplz

**Comment by LucileDT** [comment]
Done, storie n°31

**Comment by LucileDT** [comment]
### Tests utilisateur
@Eorlingalss ou @MrVarren, pourriez-vous tester les différents items de la liste ci-dessous et les cocher s'ils sont ok ?

- [x] "joli" formulaire de connexion
  - [x] form dans la nav bar
  - [x] éditer placeholder login pour y mettre "Adresse mail ou Pseudo"
- [ ] formulaire de connexion qui fonctionne
    - [x] messages
      - [x] si login !ok : message "login incorrect"
      - [ ] si login ok && mdp !ok : message "mdp incorrect"
    - [x] fonctionnement
      - [x] si login ok && mdp ok : 
        - [x] redirection vers accueil
        - [x] affichage du dropdown utilisateur
        - [x] affichage de l'icône de notifs

Pour chaque item qui n'est pas bon, vous pouvez laisser un commentaire sur cette issue en utilisant le modèle suivant : 
```markdown
### Page
url de la page

### Scénario
- étape 1 à faire
- étape 2 à faire
...
- étape n à faire

### Comportement attendu
ce que l'application devrait faire normalement

### Comportement observé
ce que l'application fait (qui est donc différent du comportement attendu)
```

Exemple :
```markdown
### Page
http://127.0.0.1:8000/

### Scénario
- entrer un login invalide
- entrer un mot de passe quelconque
- cliquer sur "se connecter"

### Comportement attendu
- un message d'erreur disant que le login est incorrect est affiché

### Comportement observé
- la page se rafraîchit sans afficher de message
```

Merciii :blue_heart:

**Comment by Eorlingalss** [comment]
### Page : 
127.0.0.1:8000

### Scénario : 
- Entrée valide des ID
- Connexion

### Comportement observé : 
- Message d'accueil disant " Bienvenue Eorlingalss"

### Comportement attendu: 
- Message d'accueil disant " Bienvienue Eorlingalss"

**Comment by Eorlingalss** [comment]
### Page : 
127.0.0.1:8000 ( avant connexion)

### Scénario : 
Entrée invalide du username et du password

### Comportement observé : 
Login et mdp incorrect ( REF : -> si login !ok : message "login incorrect"
 si login ok && mdp !ok : message "mdp incorrect")

### Comportement attendu : 
" Login incorrect"

**Comment by LucileDT** [comment]
J'ai édité ton premier commentaire, est-ce que tu peux faire pareil pour le deuxième ? Tu peux regarder les exemples pour voir comment on fait.

**Comment by LucileDT** [comment]
@hundrex si tu peux corriger le message de bienvenue, ça serait super stp !

**Comment by V-Tommy** [comment]
[Message de bienvenue corrigé ](https://github.com/AAAsso/aaaccueil/issues/1#issuecomment-313096718)

**Comment by LucileDT** [comment]
[Erreur de Message de login invalide](https://github.com/AAAsso/aaaccueil/issues/1#issuecomment-313097234)
