### ISSUE TITLE
Pop-up de suppression mal fichue

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/aaaccueil#17]
### Page
Monitorings > Détails d'un monitoring

### Scénario
- Cliquer sur Supprimer ce monitoring

### Comportement attendu
- Une modal s'ouvre pour confirmer la suppression

### Comportement observé
- La modal s'ouvre mais le texte est aligné à droite
![capture du 2017-07-08 23-09-40](https://user-images.githubusercontent.com/23707217/27989147-99e2662a-6432-11e7-8237-17c96f2ff7c6.png)

**Comment by V-Tommy** [comment]
[Résolution du problème, fermeture de l'issue](https://github.com/AAAsso/aaaccueil/issues/17#issue-241480427)
