### ISSUE TITLE
la liste des services qu'on fournit (noté AAApplications) (#5 dans le backlog)

### ISSUE THREAD

**Issue by Eorlingalss** [AAAsso/aaaccueil#6]
- [x] Création 
    - [x] Apparence 
    - [x] Fonctionnement 
- [x] Édition
    - [x] Apparence 
    - [x] Fonctionnement
- [x] Aperçu 
    - [x] Apparence 
       - [x] avec url
       - [x] quand il n'y a pas d'url
    - [x] Fonctionnement 
- [x] Suppression 
    - [x] Fonctionnement 
    - [x] Modal de confirmation avant suppression
- [x] Liste
    - [x] Apparence 
    - [x] Fonctionnement 
- [x] Barre de navigation
    - [x] Apparence
    - [x] Fonctionnement

**Comment by LucileDT** [comment]
@Parmifer dans la création d'une application, le formulaire a le champ "URL" en required alors qu'il ne faut pas. Peux-tu le rendre optionnel ? Thx.

**Comment by LucileDT** [comment]
@Parmifer il faut également qu'on affiche les applications dynamiquement dans la navbar (en fonction de la connexion utilisateur), la liste actuelle est moisie, merciiii :blue_heart:

**Comment by LucileDT** [comment]
- [ ] tester détails application quand il n'y a pas d'url

**Comment by LucileDT** [comment]
@Parmifer pour ce qui est de la population dynamique de la navbar, voir ici : https://stackoverflow.com/questions/7148404/symfony2-populate-navigation-bar-in-layout-html-twig-on-every-page-request

D'autres dropdown en ont besoin, donc si tu le fais une fois et m'explique, je pourrai le faire pour les autres :slightly_smiling_face: 

BTW tout ce que je pouvais faire facilement sur les applications est fait ! :tada:

**Comment by Parmifer** [comment]
All good, plus que la validation du form.

**Comment by Eorlingalss** [comment]
**Test utilisateur**

- [x] Création 
    - [x] Apparence 
    - [x] Fonctionnement 
- [x] Édition
    - [x] Apparence 
    - [x] Fonctionnement
- [x] Aperçu 
    - [x] Apparence 
       - [x] avec url
       - [x] quand il n'y a pas d'url
    - [x] Fonctionnement 
- [x] Suppression 
    - [x] Fonctionnement 
    - [x] Modal de confirmation avant suppression
- [x] Liste
    - [x] Apparence 
    - [x] Fonctionnement 
- [x] Barre de navigation
    - [x] Apparence
    - [x] Fonctionnement
